#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#define F_CPU 16000000UL
#define BAUD 115200UL

#define THERM_PIN 0

#define LCD_RS PORTD4
#define LCD_E PORTD3
#define LCD_DP4 PORTC5
#define LCD_DP5 PORTC4
#define LCD_DP6 PORTC3
#define LCD_DP7 PORTD2

#define LCD_DDR_RS DDD4
#define LCD_DDR_E DDD3
#define LCD_DDR_DP4 DDC5
#define LCD_DDR_DP5 DDC4
#define LCD_DDR_DP6 DDC3
#define LCD_DDR_DP7 DDD2

#endif // BOARD_CONFIG_H
